sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc
  - clang

cache:
  directories:
  - download-cache

install:
  - docker run --name testContainer -d -v $(pwd):/opt/code openresty/openresty:bionic sleep 1h
  - docker exec -ti testContainer apt-get install -qq -y cpanminus axel
  - docker exec -ti testContainer cpanm --notest Test::Nginx
  - docker exec -ti testContainer luarocks install date 2.2-2

script:
  - docker exec -ti testContainer bash -c "cd /opt/code; prove -r t"

after_script:
  - docker rm -f testContainer
